config/routes.rb
TravelBlog::Application.routes.draw do
  devise_for :users

  devise_scope :user do
    get '/login', to: 'devise/sessions#new'
  end

  resources :markers
  resources :users do
    get '/trips', action: :trips, on: :member
  end
  resources :trips

  match '/trip_interface', to: 'trips#trip_interface', as: :trip_interface

  get '/my_profile', to: 'users#my_profile', as: :my_profile
  get 'search', to: "home#search", as: :search
  root :to => 'home#home'

end

app/models/trip.rb
require "base64"
class Trip < ActiveRecord::Base
  belongs_to :user
  has_many :markers, dependent: :destroy

  attr_accessible :cover_photo, :description, :name, :user

  mount_uploader :cover_photo, TripCoverPhotoUploader

  validate :cover_photo_size_validation

  validates :name, presence: true, length:{maximum: 46}
  validates :description, length:{maximum:140}

  accepts_nested_attributes_for :markers

  class << self
    def search_results query
      where(id: select('trips.id').joins(:markers).where(
        [search_query, Marker.search_query].join(' or '),
        search: "%#{query}%"))
    end

    def search_query
      'LOWER(trips.name) like :search OR LOWER(trips.description) like :search '
    end
  end

  def decode_base64 data
    data = Base64.decode64 data.gsub(/^data:.+,/, '')
    file = Tempfile.new ["thumbnail", ".png"]
    file.binmode
    file.write data
    self.cover_photo = file
  end

  private
  def cover_photo_size_validation
    errors[:cover_photo] << "should be less than 1MB" if cover_photo.size > (1.2).megabyte
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  load_and_authorize_resource

  # GET /trips
  # GET /trips.json
  def index
    @trips = Trip.all
    # @trips = Trip.where(user_id: current_user.id)

    respond_to do |format|
      format.html # index.html.erb
      format.json {
        render json: @trips.to_json(include: :markers)
      }
    end
  end

  # GET /trips/1
  # GET /trips/1.json
  def show
    @trip = Trip.find(params[:id])
    @markers = @trip.markers
    @marker = Marker.new trip: @trip
    respond_to do |format|
      format.html # show.html.erb
      format.json {
        render :json => {
          :trip => @trip,
          :markers => @markers
          }
        }
      format.pdf do
        pdf = TripPdf.new @trip
        send_data(pdf.render, {
          filename: "#{@trip.name}.pdf",
          type: "application/pdf",
          disposition: "inline"
          })
      end
    end
  end

  # GET /trips/new
  # GET /trips/new.json
  def new
    @trip = Trip.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @trip }
    end
  end


  def trip_interface
    @trip  = Trip.new
    @marker = @trip.markers.new
    render :trip_interface
  end

  # GET /trips/1/edit
  def edit
    @trip = Trip.find(params[:id])
    markers = @trip.markers.where(trip_id: @trip.id)
  end

  # POST /trips
  # POST /trips.json
  def create
    @trip = Trip.new(name: params[:name], description: params[:description])
    @trip.decode_base64 params[:fileData] if params[:fileData]
    @trip.user  =  current_user
    if @trip.save
        render json: @trip
    else
      render json: @trip.errors.to_json, status: 422
    end
  end

  # PUT /trips/1
  # PUT /trips/1.json
  def update
    @trip = Trip.find(params[:id])

    respond_to do |format|
      if @trip.update_attributes(params[:trip])
        format.html { redirect_to @trip, notice: 'Trip was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trips/1
  # DELETE /trips/1.json
  def destroy
    @trip = Trip.find(params[:id])
    @trip.destroy

    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/trips/_form.html.erb
<%= form_for(@trip) do |f| %>
  <% if @trip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trip.errors.count, "error") %> prohibited this trip from being saved:</h2>

      <ul>
      <% @trip.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, class:"input_field" %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, :size => "26x5", class:"input_field" %>
  </div>
  <div class="field">
    <%= f.label :cover_photo%><br />
    <%= f.file_field :cover_photo, class: "centered", :onchange =>"validateFiles(this);", :data => { :max_file_size => 1.megabyte } %>
  </div>
  <div class="actions">
    <br>
    <%= f.submit "Update", class:"btn btn-sm btn-primary"  %>
  </div>
<% end %>

app/views/trips/edit.html.erb
<% @body_class = "edit_trip" %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="sign_up_form">
      <h2>Edit your trip details</h2>

        <%= render 'form' %>

      <%= link_to 'Cancel', :back %>
    </div>
  </div>
</div>

app/views/trips/index.html.erb
<h1>Trips</h1>

<table class="table">
  <tr>
    <th></th>
    <th>Name</th>
    <th>Description</th>
    <th>Traveler</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @trips.each do |trip| %>
  <tr>
    <td><%=link_to( image_tag(trip.cover_photo.mini.url), trip )%></td>
    <td><%= link_to trip.name, trip %></td>
    <td><%= trip.description %></td>
    <td><%= link_to trip.user.username, trip.user %></td>

        <% if can? :update, trip.user %>
          <td><%= link_to 'Edit', edit_trip_path(trip) %></td>
          <td><%= link_to 'Destroy', trip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end%>
  </tr>
<% end %>
</table>

<br />

app/views/trips/new.html.erb
<h1>New trip</h1>

<%= render 'form' %>

<%= link_to 'Back', trips_path %>

app/views/trips/show.html.erb
<p id="notice"><%= notice %></p>

<% content_for :map do %>
  <div id="googleMap"></div>
<% end %>

  <div id="trip_details">
    <h2>
      <%= @trip.name %>
    </h2>
    <%  unless @trip.cover_photo.thumb.nil? || @trip.cover_photo.thumb.blank? %>
    <p>
      <%=image_tag @trip.cover_photo.thumb %>
    </p>
    <% end %>
    <p>
      <b>Description:</b>
      <%= @trip.description %>
    </p>

    <p>
      <b>Traveler:</b>
      <%=link_to @trip.user.firstname, user_path(@trip.user_id)%>
    </p>

    <p>
      <b>Locations visited:</b>
      <ul> <% @trip.markers.each do |marker| %>
        <li><%= link_to marker.name, marker_path(marker.id) if marker.id %></li>
                <%end%>
      </ul>
    </p>

    <div id="trip_show_links">
      <% if can? :edit, @trip %>
        <button type=button class="btn btn-sm btn-primary" id="add_another_marker_link" >Add Another Stop</button>
      <%end%>
      <p>
        <% if can? :edit, @trip %>
          <%= link_to 'Edit', edit_trip_path(@trip) %> |
        <%end%>
        <% if can? :destroy, @trip %>
          <%= link_to 'Delete', @trip, method: :delete, data: { confirm: 'Are you sure?' } %>
        <%end%>
      </p>
    </div>

    <div class="tweet">
      <p>Love this trip?<br>Tweet about it!</p>
      <a href="https://twitter.com/share" class="twitter-share-button" data-lang="en" data-url="http://footsteps-blog.herokuapp.com/" data-text="Check out this awesome trip itinerary!" data-count="none" data-hashtags="FootSteps">Tweet</a>
    </div>



  </div>

  <div id="add_marker">
    <%= render "partials/add_marker", marker: @marker %>
  </div>

<script>
  window.markers = <%= raw @trip.markers.to_json%>
</script>

  <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>

app/views/trips/trip_interface.html.erb
<% content_for :map do %>
  <div id="googleMap"></div>
<% end %>

  <div id="form_interface">
    <%= render "partials/new_trip",  trip: @trip %>
    <%= render "partials/new_marker",  marker: @marker %>
  </div>