config/routes.rb
TravelBlog::Application.routes.draw do
  devise_for :users

  devise_scope :user do
    get '/login', to: 'devise/sessions#new'
  end

  resources :markers
  resources :users do
    get '/trips', action: :trips, on: :member
  end
  resources :trips

  match '/trip_interface', to: 'trips#trip_interface', as: :trip_interface

  get '/my_profile', to: 'users#my_profile', as: :my_profile
  get 'search', to: "home#search", as: :search
  root :to => 'home#home'

end

app/models/marker.rb
require "base64"
class Marker < ActiveRecord::Base
  belongs_to :trip

  attr_accessible :address, :description, :latitude, :longitude, :name, :trip, :photo

  mount_uploader :photo, MarkerPhotoUploader

  validate :photo_size_validation

  validates :address, presence: true
  validates :description, presence: true
  validates :name, presence: true

  geocoded_by :address

  after_validation :geocode, :if => :address_changed?

  class << self
    def search_results query
      self.where(search_query, search: "%#{query}%")
    end

    def search_query
      "LOWER(markers.name) like :search OR LOWER(markers.description) like :search OR LOWER(markers.address) like :search"
    end
  end

  def decode_base64 data
    data = Base64.decode64 data.gsub(/^data:.+,/, '')
    file = Tempfile.new ["thumbnail", ".png"]
    file.binmode
    file.write data
    self.photo = file
  end

  private
  def photo_size_validation
    errors[:photo] << "should be less than 1MB" if photo.size > (1.2).megabyte
  end
end

app/controllers/markers_controller.rb
class MarkersController < ApplicationController
  load_and_authorize_resource
  # GET /markers
  # GET /markers.json
  def index
    @markers = Marker.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @markers }
    end
  end

  # GET /markers/1
  # GET /markers/1.json
  def show
    @marker = Marker.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @marker }
    end
  end

  # GET /markers/new
  # GET /markers/new.json
  def new
    @marker = Marker.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @marker }
    end
  end

  def trip_interface
    @trip  = Trip.new
    @marker = @trip.markers.new
    render :trip_interface
  end

  # GET /markers/1/edit
  def edit
    @marker = Marker.find(params[:id])
  end

  # POST /markers
  # POST /markers.json
  def create
    @trip = current_user.trips.find(params[:trip_id])
    if @trip
      marker = @trip.markers.new params[:marker]
      marker.decode_base64 params[:fileData] if params[:fileData]
      if marker.save
        render json: marker
      else
        render json: marker.errors.to_json, status: 422
      end
    else
      render json: {error: "Something went wrong"}, status: 422
    end
  end

  # PUT /markers/1
  # PUT /markers/1.json
  def update
    @marker = Marker.find(params[:id])

    respond_to do |format|
      if @marker.update_attributes(params[:marker])
        format.html { redirect_to @marker, notice: 'Marker was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @marker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /markers/1
  # DELETE /markers/1.json
  def destroy
    @marker = Marker.find(params[:id])
    @marker.destroy

    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/markers_helper.rb
module MarkersHelper
end

app/views/markers/_form.html.erb
<%= form_for(@marker) do |f| %>
  <% if @marker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@marker.errors.count, "error") %> prohibited this marker from being saved:</h2>

      <ul>
      <% @marker.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, class:"input_field" %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, :size => "30x5", class:"input_field" %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address, class:"input_field" %>
  </div>
  <div class="field links">
    <%= f.label :photo %><br>
    <%= f.file_field :photo, class: "centered", :onchange =>"validateFiles(this);", :data => { :max_file_size => 1.megabyte }%><br/><br>
</div>
  <div class="actions">
    <br>
    <%= f.submit "Update", class:"btn btn-sm btn-primary"  %>
  </div>
<% end %>

app/views/markers/edit.html.erb
<% @body_class = "edit_marker" %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="sign_up_form">
      <h2>Edit your stop details</h2>

        <%= render 'form' %>

      <%= link_to 'Cancel', :back %>
    </div>
  </div>
</div>

app/views/markers/index.html.erb
<h1>Stops</h1>

<table>
  <tr>
    <th></th>
    <th>Stop Name</th>
    <th>Description</th>
    <th>Location</th>
    <th>Full Trip</th>
    <th></th>
    <th></th>
  </tr>

<% @markers.each do |marker| %>
  <tr>
    <td><%=link_to( image_tag(marker.photo.mini.url), marker ) %></td>
    <td><%= link_to marker.name, marker %></td>
    <td><%= marker.description %></td>
    <td><%= marker.address %></td>
    <td><%= link_to marker.trip.name, marker.trip %></td>

        <% if can? :update, marker.trip.user %>
            <td><%= link_to 'Edit', edit_marker_path(marker) %>    </td>
            <td><%= link_to 'Destroy', marker, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end%>
  </tr>
<% end %>
</table>

<br />

app/views/markers/new.html.erb
<h1>New marker</h1>

<%= render 'form' %>

<%= link_to 'Back', markers_path %>

app/views/markers/show.html.erb
<div><p id="notice"><%= notice %></p></div>

<% content_for :map do %>
  <div id="googleMap_marker"></div>
<% end %>

<div id="trip_details">

  <h2>
    <%= @marker.name %>
  </h2>

  <%  unless @marker.photo.thumb.nil? || @marker.photo.thumb.blank? %>
    <p>
      <%=image_tag @marker.photo.thumb %>
    </p>
  <% end %>



  <p>
    <b>Description:</b>
    <%= @marker.description %>
  </p>

  <p>
    <b>Location:</b>
    <%= @marker.address %>
  </p>

  <p  >
    <b>Latitude:</b>
    <span id="latitude" ><%= @marker.latitude %></span>
  </p>

  <p>
    <b>Longitude:</b>
    <span  id="longitude"><%= @marker.longitude %></span>
  </p>

  <p>
    <b>Trip:</b>
    <%= link_to @marker.trip.name, trip_path(@marker.trip_id) %>
  </p>

  <p>
    <b>Traveler:</b>
    <%= link_to @marker.trip.user.username, user_path(@marker.trip.user_id) %>
  </p>
  <div class="links">
  <% if can? :edit, @marker %>
    <%= link_to 'Edit', edit_marker_path(@marker) %> |
  <%end%>
  <% if can? :destroy, @marker %>
    <%= link_to 'Delete', @marker, method: :delete, data: { confirm: 'Are you sure?' } %> |
  <%end%>
  <%= link_to 'Back', :back %>
  </div>
</div>