config/routes.rb
TravelBlog::Application.routes.draw do
  devise_for :users

  devise_scope :user do
    get '/login', to: 'devise/sessions#new'
  end

  resources :markers
  resources :users do
    get '/trips', action: :trips, on: :member
  end
  resources :trips

  match '/trip_interface', to: 'trips#trip_interface', as: :trip_interface

  get '/my_profile', to: 'users#my_profile', as: :my_profile
  get 'search', to: "home#search", as: :search
  root :to => 'home#home'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="<%=@body_class%>" >
<head>
  <title>Footsteps</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE']}&sensor=false" %>

  <%= csrf_meta_tags %>
</head>
<body class="<%=@body_class%>" <%= yield :user_id %>>

  <%= yield :map %>

  <nav class="navbar navbar-inverse" role="navigation">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex8-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
      </button>
      <%= link_to("FootSteps", root_path, class: "navbar-brand") %>
    </div>
    <div class="collapse navbar-collapse navbar-ex8-collapse">
      <ul class="nav navbar-nav">
        <% if can? :create, Trip %>
          <li><%= link_to('Create New Trip', trip_interface_path)  %></li>
        <% else %>
          <li><%= link_to('Create New Trip', login_path)  %></li>
        <% end %>
        <%if  can? :manage ,:all %>
          <li><%= link_to('Trips', trips_path)  %></li>
          <li><%= link_to('Stops', markers_path)  %></li>
          <li><%= link_to('Travelers', users_path)  %></li>
          <% end %>
        <% if current_user %>
          <li><%= link_to('My Profile', my_profile_path) %></li>
        <% end %>
        <% unless request.env["PATH_INFO"] == "/" %>
          <li>
            <%= form_tag root_path, class:"navbar-form navbar-left", id:"navbar_submit_form_button", html: {method: :post} do |f| %>
              <div class="form-group">
                <%= text_field_tag :q, params[:q], class:"form-control input-sm nav_search"%>
              </div>
            </li>
            <li>
              <%= image_submit_tag("search_icon_white.png", id: "search_icon") %>
            <% end %>
          </li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% unless current_user %>
        <li class="nav-signup"><%= link_to('Sign up', new_user_registration_path)  %></li>
        <% end %>

        <li class="nav-user">
          <% if current_user %>
            <%= link_to "Log Out, #{current_user.username.humanize}!" , destroy_user_session_path, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% else %>
            <%= link_to 'Login', login_path %>
          <% end %>
        </li>
      </ul>
    </div>
  </nav>

<div class="container">
  <%= yield %>
</div>

  <footer>
    <%= yield :scripts %>
  </footer>
</body>
</html>